# Generated by Django 4.2.30 on 2026-05-08 06:19

import cases.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('project', models.CharField(blank=True, max_length=200, null=True)),
                ('court_name', models.CharField(max_length=200)),
                ('case_type', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('family', 'Family'), ('corporate', 'Corporate'), ('property', 'Property'), ('labour', 'Labour'), ('tax', 'Tax'), ('constitutional', 'Constitutional'), ('other', 'Other')], default='civil', max_length=50)),
                ('filing_date', models.DateField()),
                ('last_hearing_date', models.DateField(blank=True, null=True)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('disposed', 'Disposed'), ('on_hold', 'On Hold')], default='in_progress', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('petitioner', models.CharField(blank=True, max_length=255)),
                ('respondent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role__in': ['lawyer', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('folder', models.CharField(blank=True, help_text='Optional folder label e.g. Pleadings', max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('document_type', models.CharField(choices=[('petition', 'Petition'), ('evidence', 'Evidence'), ('order', 'Court Order'), ('affidavit', 'Affidavit'), ('notice', 'Notice'), ('judgment', 'Judgment'), ('contract', 'Contract'), ('correspondence', 'Correspondence'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(upload_to=cases.models.document_upload_path, validators=[cases.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order_details', models.TextField(blank=True, help_text='Order details / key directions from court')),
                ('filing_response', models.TextField(blank=True, help_text='What was filed/submitted in response')),
                ('response_received', models.TextField(blank=True, help_text='What response was received from court/opposite side')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal case notes for this timeline entry')),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_document', models.ForeignKey(blank=True, help_text='Legacy single document link (kept for compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_updates', to='cases.casedocument')),
            ],
            options={
                'verbose_name': 'Case Update',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hours', models.DecimalField(decimal_places=2, help_text='Hours spent (e.g. 1.5 = 1h 30m)', max_digits=5)),
                ('description', models.CharField(help_text='What was done (e.g. Drafted reply, Attended hearing)', max_length=300)),
                ('is_billable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='cases.case')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Entry',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfflineDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('folder', models.CharField(blank=True, help_text='Optional folder label', max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('storage_location', models.CharField(blank=True, help_text='Physical location e.g. Rack A / Box 4 / Chamber file shelf', max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='offline_documents/%Y/%m/', validators=[cases.models.validate_file_size])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_documents', to='cases.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offline Document',
                'verbose_name_plural': 'Offline Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('hearing', 'Upcoming Hearing'), ('deadline', 'Deadline Due'), ('task', 'Task Assigned'), ('overdue', 'Overdue Item'), ('update', 'Case Updated'), ('system', 'System')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HearingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField(help_text='Date this hearing took place or is scheduled')),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(help_text='Purpose / agenda of this hearing', max_length=300)),
                ('judge_name', models.CharField(blank=True, help_text='Judge or bench before whom the matter was listed', max_length=150)),
                ('outcome_notes', models.TextField(blank=True, help_text='What happened / result of this hearing')),
                ('scrape_url', models.URLField(blank=True, help_text='eCourt or court website URL to auto-fetch hearing data')),
                ('scraped_data', models.TextField(blank=True, help_text='Raw text scraped from court website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearing_records', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hearing Record',
                'ordering': ['-hearing_date'],
            },
        ),
        migrations.CreateModel(
            name='GlobalAlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text='Label e.g. Ops Team', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Alert Recipient',
                'verbose_name_plural': 'Global Alert Recipients',
                'ordering': ['name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cases.case')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Task',
                'ordering': ['is_completed', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('won', 'Won'), ('lost', 'Lost'), ('settled', 'Settled'), ('withdrawn', 'Withdrawn'), ('dismissed', 'Dismissed'), ('transferred', 'Transferred'), ('other', 'Other')], max_length=20)),
                ('disposed_date', models.DateField(default=django.utils.timezone.now)),
                ('summary', models.TextField(blank=True, help_text='Brief summary of how the case was resolved')),
                ('judge_name', models.CharField(blank=True, max_length=150)),
                ('opposing_counsel', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='cases.case')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Outcome',
            },
        ),
        migrations.CreateModel(
            name='CaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Case Created'), ('edited', 'Field Changed'), ('status', 'Status Changed'), ('assigned', 'Lawyer Reassigned'), ('hearing', 'Hearing Date Changed'), ('hearing_record', 'Hearing Record Added'), ('court_order', 'Court Order PDF Added'), ('document', 'Document Event'), ('update', 'Case Update Added'), ('task', 'Task Event'), ('deadline', 'Deadline Event'), ('outcome', 'Outcome Recorded'), ('note', 'Manual Note')], max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Which field changed (e.g. status, court_name)', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value')),
                ('new_value', models.TextField(blank=True, help_text='New value')),
                ('description', models.TextField(blank=True, help_text='Human-readable summary of the event')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='cases.case')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case History',
                'verbose_name_plural': 'Case History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='cases.case')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deadlines', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deadlines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Deadline',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseCourtOrderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_label', models.CharField(blank=True, help_text='Text shown as the link (e.g. W.P.(C)-IPD 31/2025). Leave blank to use this case’s case number.', max_length=200)),
                ('pdf_url', models.URLField(help_text='Full URL to the order PDF (opens in a new tab)', max_length=1000)),
                ('order_date', models.DateField(help_text='Date of the order')),
                ('judge_name', models.CharField(blank=True, help_text='Judge or bench (optional)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_order_links', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_order_links_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Court order PDF link',
                'verbose_name_plural': 'Court order PDF links',
                'ordering': ['-order_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='HearingEmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, help_text='Label e.g. Client, Partner', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_recipients', to='cases.case')),
            ],
            options={
                'verbose_name': 'Hearing Email Recipient',
                'ordering': ['name', 'email'],
                'unique_together': {('case', 'email')},
            },
        ),
        migrations.CreateModel(
            name='HearingAlertOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address that opted out', max_length=254)),
                ('token', models.CharField(help_text='Secure token embedded in the email link', max_length=64, unique=True)),
                ('reason', models.CharField(blank=True, choices=[('preparing', 'Already preparing for the hearing'), ('acknowledged', 'Already acknowledged / aware'), ('attending', 'Confirmed attendance'), ('not_relevant', 'Not relevant to me'), ('other', 'Other')], max_length=20)),
                ('custom_note', models.TextField(blank=True, help_text='Optional free-text reason')),
                ('hearing_date', models.DateField(help_text='Which hearing date this opt-out is for')),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='True = stop 7-day reminders, still send 1-day alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_opt_outs', to='cases.case')),
            ],
            options={
                'verbose_name': 'Hearing Alert Opt-Out',
                'unique_together': {('case', 'email', 'hearing_date')},
            },
        ),
        migrations.CreateModel(
            name='ClientCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('can_view_documents', models.BooleanField(default=True)),
                ('can_view_updates', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_grants', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_accesses', to='cases.case')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='accessible_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Case Access',
                'unique_together': {('client', 'case')},
            },
        ),
        migrations.CreateModel(
            name='CaseUpdateDocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.caseupdate')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_attachments', to='cases.casedocument')),
            ],
            options={
                'verbose_name': 'Case Update Document Attachment',
                'ordering': ['-created_at'],
                'unique_together': {('case_update', 'document')},
            },
        ),
    ]
