# Generated by Django 4.2.30 on 2026-05-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='casedocument',
            table='case_documents',
        ),
        migrations.AlterModelTable(
            name='casehistory',
            table='case_history',
        ),
    ]
